; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -mtriple=riscv64 -passes=slp-vectorizer -S | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @abc(i64 %0, ptr %1) {
; CHECK-LABEL: define void @abc(
; CHECK-SAME: i64 [[TMP0:%.*]], ptr [[TMP1:%.*]]) {
; CHECK-NEXT:  [[NEWFUNCROOT:.*:]]
; CHECK-NEXT:    br label %[[IF_ELSE43:.*]]
; CHECK:       [[IF_ELSE43]]:
; CHECK-NEXT:    [[CONV44:%.*]] = sitofp i64 [[TMP0]] to double
; CHECK-NEXT:    [[DIV45:%.*]] = fdiv double [[CONV44]], 1.000000e+03
; CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.ceil.f64(double [[DIV45]])
; CHECK-NEXT:    [[CONV46:%.*]] = fptosi double [[TMP2]] to i32
; CHECK-NEXT:    [[DIV48:%.*]] = fdiv double [[CONV44]], 1.000000e+01
; CHECK-NEXT:    [[TMP3:%.*]] = tail call double @llvm.ceil.f64(double [[DIV48]])
; CHECK-NEXT:    [[CONV49:%.*]] = fptosi double [[TMP3]] to i32
; CHECK-NEXT:    [[CMP52_NOT170:%.*]] = icmp sgt i32 [[CONV46]], [[CONV49]]
; CHECK-NEXT:    br label %[[EXIT_EXITSTUB:.*]]
; CHECK:       [[EXIT_EXITSTUB]]:
; CHECK-NEXT:    store i1 [[CMP52_NOT170]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
newFuncRoot:
  br label %if.else43

if.else43:                                        ; preds = %newFuncRoot
  %conv44 = sitofp i64 %0 to double
  %div45 = fdiv double %conv44, 1.000000e+03
  %2 = tail call double @llvm.ceil.f64(double %div45)
  %conv46 = fptosi double %2 to i32
  %div48 = fdiv double %conv44, 1.000000e+01
  %3 = tail call double @llvm.ceil.f64(double %div48)
  %conv49 = fptosi double %3 to i32
  %cmp52.not170 = icmp sgt i32 %conv46, %conv49
  br label %exit.exitStub

exit.exitStub:                                    ; preds = %if.else43
  store i1 %cmp52.not170, ptr %1, align 1
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.ceil.f64(double) #0

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.floor.f64(double) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
