; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -mtriple=riscv64 -passes=slp-vectorizer -S | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @abc(ptr %0) {
; CHECK-LABEL: define void @abc(
; CHECK-SAME: ptr [[TMP0:%.*]]) {
; CHECK-NEXT:  [[NEWFUNCROOT:.*:]]
; CHECK-NEXT:    br label %[[ENTRY:.*]]
; CHECK:       [[ENTRY]]:
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 8
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[ARRAYIDX1]], align 8, !tbaa [[DOUBLE_TBAA0:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 32
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[ARRAYIDX2]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP2]], ptr [[ARRAYIDX1]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP1]], ptr [[ARRAYIDX2]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 16
; CHECK-NEXT:    [[TMP3:%.*]] = load double, ptr [[ARRAYIDX9]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 64
; CHECK-NEXT:    [[TMP4:%.*]] = load double, ptr [[ARRAYIDX10]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP4]], ptr [[ARRAYIDX9]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP3]], ptr [[ARRAYIDX10]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 48
; CHECK-NEXT:    [[TMP5:%.*]] = load double, ptr [[ARRAYIDX17]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 72
; CHECK-NEXT:    [[TMP6:%.*]] = load double, ptr [[ARRAYIDX19]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP6]], ptr [[ARRAYIDX17]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP5]], ptr [[ARRAYIDX19]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 88
; CHECK-NEXT:    [[TMP7:%.*]] = load double, ptr [[ARRAYIDX25]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 96
; CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 112
; CHECK-NEXT:    [[TMP8:%.*]] = load double, ptr [[ARRAYIDX27]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP8]], ptr [[ARRAYIDX25]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP7]], ptr [[ARRAYIDX27]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[TMP9:%.*]] = load double, ptr [[ARRAYIDX26]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX35:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 24
; CHECK-NEXT:    [[TMP10:%.*]] = load double, ptr [[ARRAYIDX35]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP10]], ptr [[ARRAYIDX26]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP9]], ptr [[ARRAYIDX35]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX41:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 104
; CHECK-NEXT:    [[TMP11:%.*]] = load double, ptr [[ARRAYIDX41]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX43:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 56
; CHECK-NEXT:    [[TMP12:%.*]] = load double, ptr [[ARRAYIDX43]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP12]], ptr [[ARRAYIDX41]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    store double [[TMP11]], ptr [[ARRAYIDX43]], align 8, !tbaa [[DOUBLE_TBAA0]]
; CHECK-NEXT:    br label %[[EXIT_EXITSTUB:.*]]
; CHECK:       [[EXIT_EXITSTUB]]:
; CHECK-NEXT:    ret void
;
newFuncRoot:
  br label %entry

entry:                                            ; preds = %newFuncRoot
  %arrayidx1 = getelementptr inbounds i8, ptr %0, i64 8
  %1 = load double, ptr %arrayidx1, align 8, !tbaa !0
  %arrayidx2 = getelementptr inbounds i8, ptr %0, i64 32
  %2 = load double, ptr %arrayidx2, align 8, !tbaa !0
  store double %2, ptr %arrayidx1, align 8, !tbaa !0
  store double %1, ptr %arrayidx2, align 8, !tbaa !0
  %arrayidx9 = getelementptr inbounds i8, ptr %0, i64 16
  %3 = load double, ptr %arrayidx9, align 8, !tbaa !0
  %arrayidx10 = getelementptr inbounds i8, ptr %0, i64 64
  %4 = load double, ptr %arrayidx10, align 8, !tbaa !0
  store double %4, ptr %arrayidx9, align 8, !tbaa !0
  store double %3, ptr %arrayidx10, align 8, !tbaa !0
  %arrayidx17 = getelementptr inbounds i8, ptr %0, i64 48
  %5 = load double, ptr %arrayidx17, align 8, !tbaa !0
  %arrayidx19 = getelementptr inbounds i8, ptr %0, i64 72
  %6 = load double, ptr %arrayidx19, align 8, !tbaa !0
  store double %6, ptr %arrayidx17, align 8, !tbaa !0
  store double %5, ptr %arrayidx19, align 8, !tbaa !0
  %arrayidx25 = getelementptr inbounds i8, ptr %0, i64 88
  %7 = load double, ptr %arrayidx25, align 8, !tbaa !0
  %arrayidx26 = getelementptr inbounds i8, ptr %0, i64 96
  %arrayidx27 = getelementptr inbounds i8, ptr %0, i64 112
  %8 = load double, ptr %arrayidx27, align 8, !tbaa !0
  store double %8, ptr %arrayidx25, align 8, !tbaa !0
  store double %7, ptr %arrayidx27, align 8, !tbaa !0
  %9 = load double, ptr %arrayidx26, align 8, !tbaa !0
  %arrayidx35 = getelementptr inbounds i8, ptr %0, i64 24
  %10 = load double, ptr %arrayidx35, align 8, !tbaa !0
  store double %10, ptr %arrayidx26, align 8, !tbaa !0
  store double %9, ptr %arrayidx35, align 8, !tbaa !0
  %arrayidx41 = getelementptr inbounds i8, ptr %0, i64 104
  %11 = load double, ptr %arrayidx41, align 8, !tbaa !0
  %arrayidx43 = getelementptr inbounds i8, ptr %0, i64 56
  %12 = load double, ptr %arrayidx43, align 8, !tbaa !0
  store double %12, ptr %arrayidx41, align 8, !tbaa !0
  store double %11, ptr %arrayidx43, align 8, !tbaa !0
  br label %exit.exitStub

exit.exitStub:                                    ; preds = %entry
  ret void
}

!0 = !{!1, !1, i64 0}
!1 = !{!"double", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C++ TBAA"}
;.
; CHECK: [[DOUBLE_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"double", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C++ TBAA"}
;.
